# Ch 12: Tuples


### Tuples Are Immutable

A tuple is a sequence of values. The values can be of any type, and they are indexed by integers, so in that respect tuples are a lot like arrays. The important difference is that tuples are immutable and that each element can have its own type. 

Syntactically, a tuple is a comma-separated list of values:

In [1]:
t = 'a', 'b', 'c', 'd', 'e'

('a', 'b', 'c', 'd', 'e')

Although it is not necessary, it is common to enclose tuples in parentheses (I would strongly recommend this practice):

In [2]:
t = ('a', 'b', 'c', 'd', 'e')

('a', 'b', 'c', 'd', 'e')

To create a tuple with a single element, you have to include a final comma:

In [3]:
t1 = ('a',)
typeof(t1)

Tuple{Char}

A value in parentheses without comma is not a tuple:

In [4]:
t2 = ('a')

'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

In [5]:
typeof(t2)

Char

Another way to create a tuple is the built-in function tuple. With no argument, it creates an empty tuple:

In [6]:
tuple()

()

If multiple arguments are provided, the result is a tuple with the given arguments:

In [7]:
t3 = tuple(1, 'a', pi)

(1, 'a', π)

Most array operators also work on tuples. The bracket operator indexes an element:

In [10]:
t = ('a', 'b', 'c', 'd', 'e');
t[1]

'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

And the slice operator selects a range of elements:

In [11]:
t[2:4]

('b', 'c', 'd')

But if you try to modify one of the elements of the tuple, you get an error. Because tuples are immutable, you can’t modify the elements!

In [12]:
t[1] = 'A'

MethodError: MethodError: no method matching setindex!(::NTuple{5,Char}, ::Char, ::Int64)

**The relational operators work with tuples and other sequences;** Julia starts by comparing the first element from each sequence. If they are equal, it goes on to the next elements, and so on, until it finds elements that differ. Subsequent elements are not considered (even if they are really big).

In [13]:
(0, 1, 2) < (0, 3, 4)

true

In [14]:
(0, 1, 2000000) < (0, 3, 4)

true

### Tuple Assignment

It is often useful to swap the values of two variables. With conventional assignments, you have to use a temporary variable. For example, to swap $a$ and $b$:

In [17]:
a = 1
b = 2
temp = a
a = b
b = temp
a, b

(2, 1)

This solution is cumbersome; tuple assignment is more elegant:

In [18]:
a, b = b, a

(1, 2)

Each value is assigned to its respective variable. All the expressions on the right side are evaluated before any of the assignments.

**The number of variables on the left has to be fewer than the number of values on the right:**

In [22]:
(a, b) = (1, 2, 3)

(1, 2, 3)

In [23]:
a

1

In [24]:
b

2

In [20]:
a, b, c = 1, 2

BoundsError: BoundsError: attempt to access (1, 2)
  at index [3]

More generally, the right side can be any kind of sequence (string, array or tuple). For example, to split an email address into a user name and a domain, you could write:

In [25]:
addr = "julius.caesar@rome"
uname, domain = split(addr, '@');

In [26]:
uname, domain

("julius.caesar", "rome")

### Tuples as Return Values

Strictly speaking, a function can only return one value, but if the value is a tuple, the effect is the same as returning multiple values. For example, if you want to divide two integers and compute the quotient and remainder, it is inefficient to compute `x ÷ y` and then `x % y`. It is better to compute them both at the same time.

The built-in function divrem takes two arguments and returns a tuple of two values, the quotient and remainder. You can store the result as a tuple:


In [27]:
t = divrem(7, 3)

(2, 1)

In [29]:
q, r = divrem(7, 3);
@show q r;

q = 2
r = 1


### Variable-length Argument Tuples

Functions can take a variable number of arguments. A parameter name that ends with `...` **gathers arguments into a tuple**. For example, printall takes any number of arguments and prints them. The gather parameter can have any name you like, but `args` is conventional.

In [30]:
function printall(args...)
    println(args)
end

printall (generic function with 1 method)

In [31]:
printall(1, 2.0, '3')

(1, 2.0, '3')


The complement of gather is **scatter**. If you have a sequence of values and you want to pass it to a function as multiple
arguments, you can use the ... operator. 

For example, `divrem` takes exactly two arguments; it doesn’t work with a tuple:

In [32]:
t = (7, 3);
divrem(t)

MethodError: MethodError: no method matching divrem(::Tuple{Int64,Int64})
Closest candidates are:
  divrem(::T, !Matched::Base.MultiplicativeInverses.MultiplicativeInverse{T}) where T at multinverses.jl:152
  divrem(::Any, !Matched::Any) at number.jl:105
  divrem(!Matched::BigInt, !Matched::BigInt) at gmp.jl:500

In [33]:
divrem(t...)

(2, 1)

In the Julia world, gather is often called “slurp” and scatter “splat”.

### Exercise 12-1

Many of the built-in functions use variable-length argument tuples. But sum does not.  Write a function called `sumall` that takes any number of arguments and returns their sum.


In [38]:
function sumall(args...)
    total = 0
    for arg in args
        total += arg
    end
    return total
end

sumall (generic function with 1 method)

In [39]:
sumall(1,2,3,4)

10

### Arrays and Tuples

`zip` is a built-in function that takes two or more sequences and returns a collection of tuples where each tuple contains one element from each sequence. The name of the function refers to a zipper, which joins and interleaves two rows of teeth.

In [40]:
s = "abc";
t = [1, 2, 3];
zip(s, t)

Base.Iterators.Zip{Tuple{String,Array{Int64,1}}}(("abc", [1, 2, 3]))

The result is a zip object that knows how to iterate through the pairs. The most common use of zip is in a for loop:

In [41]:
for pair in zip(s, t)
    println(pair)
end

('a', 1)
('b', 2)
('c', 3)


A zip object is a kind of *iterator*, which is any object that iterates through a sequence. Iterators are similar to arrays in some ways, but unlike arrays, you can’t use an index to select an element from an iterator.  Iterators are lazy (only evaluates next elements when they have to).

If you want to use array operators and functions, you can use a zip object to make an array:

In [42]:
collect(zip(s, t))

3-element Array{Tuple{Char,Int64},1}:
 ('a', 1)
 ('b', 2)
 ('c', 3)

The result is an array of tuples; in this example, each tuple contains a character from the string and the corresponding element from the array.

If the sequences are not the same length, the result has the length of the shorter one.

In [44]:
collect(zip("Anne", "Elk"))

3-element Array{Tuple{Char,Char},1}:
 ('A', 'E')
 ('n', 'l')
 ('n', 'k')

You can use tuple assignment in a for loop to traverse an array of tuples:

In [45]:
t = [('a', 1), ('b', 2), ('c', 3)];

for (letter, number) in t    # the parentheses are mandatory!!
    println(number, " ", letter)
end

1 a
2 b
3 c


#### Traversing two or more sequences at the same time

If you combine `zip`, `for` and tuple assignment, you get a useful idiom for traversing two (or more) sequences at the same
time.  

For example, `hasmatch` takes two sequences, `t1` and `t2`, and returns true if there is an index $i$ such that `t1[i] == t2[i]`:

In [46]:
function hasmatch(t1, t2)
    for (x, y) in zip(t1, t2)
        if x == y
            return true
        end
    end
    false
end

hasmatch (generic function with 1 method)

If you need to traverse the elements of a sequence and their indices, you can use the built-in function enumerate :

In [47]:
for (index, element) in enumerate("abc")
    println(index, " ", element)
end

1 a
2 b
3 c


The result from enumerate is an enumerate object, which iterates a sequence of pairs; each pair contains an index (starting from 1) and an element from the given sequence.

### Dictionaries and Tuples

Dictionaries can be used as iterators that iterate the key-value pairs. You can use it in a for loop like this:

In [48]:
d = Dict('a'=>1, 'b'=>2, 'c'=>3);

for (key, value) in d
    println(key, " ", value)
end

a 1
c 3
b 2


In [69]:
collect(d)


3-element Array{Pair{Char,Int64},1}:
 'a' => 1
 'c' => 3
 'b' => 2

Going in the other direction, you can use an array of tuples to initialize a new dictionary:

In [49]:
t = [('a', 1), ('c', 3), ('b', 2)];
d = Dict(t)

Dict{Char,Int64} with 3 entries:
  'a' => 1
  'c' => 3
  'b' => 2

**Combining Dict with zip yields a concise way to create a dictionary:**

In [51]:
d = Dict(zip("abc", 1:3))

Dict{Char,Int64} with 3 entries:
  'a' => 1
  'c' => 3
  'b' => 2

**It is common to use tuples as keys in dictionaries.**

For example, a telephone directory might map from last-name, firstname pairs to telephone numbers.

In [54]:
directory = Dict()

last1 = "Jay"
first1 = "AA"
number1 = 123456

last2 = "Kay"
first2 = "BB"
number2 = 456789


directory[(last1, first1)] = number1;
directory[(last2, first2)] = number2;

directory

Dict{Any,Any} with 2 entries:
  ("Jay", "AA") => 123456
  ("Kay", "BB") => 456789

In [55]:
for ((last, first), number) in directory
    println(first, " ", last, " ", number)
end

AA Jay 123456
BB Kay 456789


### Sequences of Sequences

We have focused on arrays of tuples, but almost all of the examples in this chapter also work with arrays of arrays, tuples of tuples, and tuples of arrays. To avoid enumerating the possible combinations, it is sometimes easier to talk about sequences of sequences.

In many contexts, the different kinds of sequences (strings, arrays and tuples) can be used interchangeably. So how should you choose one over the others?

To start with the obvious, strings are more limited than other sequences because the elements have to be characters. They are also immutable. If you need the ability to change the characters in a string (as opposed to creating a new string), you might want to use an array of characters instead. 

Arrays are more common than tuples, mostly because they are mutable. But there are a few cases where you might prefer tuples:

* In some contexts, like a return statement, it is syntactically simpler to create a tuple than an array. 

* If you are passing a sequence as an argument to a function, using tuples reduces the potential for unexpected behavior due to aliasing.

* For performance reasons. The compiler can specialize on the type.

Because tuples are immutable, they don’t provide functions like `sort!` and `reverse!`, which modify existing arrays. But Julia provides the built-in function `sort`, which takes an array and returns a new array with the same elements in sorted order, and `reverse`, which takes any sequence and returns a sequence of the same type in reverse order.

### Debugging for Compound Data Structures

Arrays, dictionaries and tuples are examples of data structures; in this lecture we are starting to see compound data structures, like arrays of tuples, or dictionaries that contain tuples as keys and arrays as values. Compound data structures are useful, but they are prone to what I call shape errors; that is, errors caused when a data structure has the wrong type, size, or structure. For example, if you are expecting an array with one integer and I give you a plain old integer (not in an array), it won’t work.

Julia allows to attach a type to elements of a sequence. How this is done is detailed in Multiple Dispatch. Specifying the type
eliminates a lot of shape errors.

### Exercise 12-2

Write a function called `mostfrequent` that takes a string and prints the letters in decreasing order of frequency. Find text samples from several different languages and see how letter frequency varies between languages. Compare your results with the tables at https://en.wikipedia.org/wiki/Letter_frequencies.



TIP: You may want to use `histogram` from the previous chpater to first build a dictionary for the frequency of letters.  Note that the letters are the keys and the frequencies are the values.

As for sorting, one approach is to zip the values and keys (in that order) of the dictionary, collect the result to create an array of tuples, and then sort.  Note that sorting is done by the first elements (values in this approach) in `sort`.

Another approach is to collect the dictionary and use `sort` with optional arguments so that it sorts by the second elements (values):

```
sort(v; alg::Algorithm=defalg(v), lt=isless, by=identity, rev::Bool=false, order::Ordering=Forward)
```


In [403]:
function histogram(s) 
    d = Dict()
    for c in s
        d[c] = get(d,c,0) + 1
    end
    d
end

function mostfrequent(s) 
    
    d = histogram(s)
    
    collect_val_key = collect( zip(values(d),keys(d)) )

    d_sorted = sort(collect_val_key, rev=true)
    
    
    for (freq, letter) in d_sorted
        println("$letter,  $freq")
    end
    
    
end


mostfrequent (generic function with 1 method)

In [404]:
mostfrequent("Hello my name is Diego")

 ,  4
e,  3
o,  2
m,  2
l,  2
i,  2
y,  1
s,  1
n,  1
g,  1
a,  1
H,  1
D,  1


In [405]:
function mostfrequent2(s) 
    
    d = histogram(s)

    d_sorted = sort(collect(d), by=x->x[2], rev=true)
    
    for (letter, freq) in d_sorted
        println("$letter,  $freq")
    end
    
    
end

mostfrequent2 (generic function with 1 method)

In [406]:
mostfrequent2("Hello my name is Diego")

 ,  4
e,  3
o,  2
i,  2
m,  2
l,  2
n,  1
D,  1
y,  1
s,  1
H,  1
a,  1
g,  1


### Exercise 12-3

More anagrams!

1. Write a program that reads a word list from a file (see Reading Word Lists) and prints all the sets of words that are anagrams. Here is an example of what the output might look like:

```
["deltas", "desalt", "lasted", "salted", "slated", "staled"]
["retainers", "ternaries"]
["generating", "greatening"]
["resmelts", "smelters", "termless"]
```

TIP: You might want to build a dictionary that maps from a collection of letters to an array of words that can be spelled with those letters.  Start by reviewing `build_words_dict`.

The question is, how can you represent the collection of letters in a way that can be used as a key?

Also, review Exercise 11-3 (`invertdictV2`).

2. Modify the previous program so that it prints the longest array of anagrams first, followed by the second longest, and so on.


3. In Scrabble a “bingo” is when you play all seven tiles in your rack, along with a letter on the board, to form an eight-letter word.  What collection of 8 letters forms the most possible bingos?

In [88]:
sorted = join(sort(collect("fight")))

"fghit"

```
filter(f, d::AbstractDict)
Return a copy of d, removing elements for which f is false. The function f is passed key=>value pairs.

Examples
julia> d = Dict(1=>"a", 2=>"b")
Dict{Int64,String} with 2 entries:
  2 => "b"
  1 => "a"

julia> filter(p->isodd(p.first), d)
Dict{Int64,String} with 1 entry:
  1 => "a"

```

In [415]:
# function build_words_dict()
    
#     dict = Dict();
    
#     for word in eachline("words.txt")
#         dict[word] = ""
#     end

#     return dict
    
# end

# words_dict = build_words_dict();


# function invertdictV2(d)
#     inverse = Dict()
    
#     for key in keys(d)
              
#         val = d[key]
#         push!( get!(inverse,val,[]), key )
        
#     end
    
#     inverse
    
# end


function build_anagram_dict()
    
    dict = Dict();
    
    for word in eachline("words.txt")
        
        sorted = join(sort(collect(word)))
        push!(get!(dict, sorted,[]), word)
        
    end
    
    # note that this dictionary contains ALL words 
    # (those words without anagrams will just have one-element arrays as the value)
    
    
#     ana_dict = Dict()  # This is a rather clumsy implementation and creates a new dictionary
#                        # We could delete key-value pairs (those with just one word) from dict
    
#     for (key,value) in dict
#         if length(value) > 1
#             ana_dict[key] = value
#         end
#     end

#     return ana_dict
    
        
    return filter( p -> length(p.second) > 1, dict )
    
end

build_anagram_dict (generic function with 1 method)

In [416]:
anagram_dict = build_anagram_dict()

Dict{Any,Any} with 10157 entries:
  "aelnprst"   => Any["planters", "replants"]
  "eeffginorr" => Any["forefinger", "reoffering"]
  "eeflstt"    => Any["fettles", "leftest"]
  "bhort"      => Any["broth", "throb"]
  "achm"       => Any["cham", "mach"]
  "aginrstw"   => Any["ringtaws", "strawing"]
  "aefl"       => Any["alef", "feal", "flea", "leaf"]
  "aefirs"     => Any["ferias", "fraise"]
  "bdilpsuu"   => Any["buildups", "upbuilds"]
  "acehss"     => Any["cashes", "chases", "chasse"]
  "dehoop"     => Any["hooped", "poohed"]
  "acegilr"    => Any["glacier", "gracile"]
  "aaceilln"   => Any["alliance", "ancillae", "canaille"]
  "mnor"       => Any["morn", "norm"]
  "entty"      => Any["netty", "tenty"]
  "adnors"     => Any["adorns", "radons"]
  "eelrsv"     => Any["elvers", "levers", "revels"]
  "aelprsty"   => Any["peytrals", "plastery", "psaltery"]
  "bginor"     => Any["boring", "orbing", "robing"]
  "deipst"     => Any["spited", "stiped"]
  "adnr"       => Any["darn", "nard", "r

In [99]:
function build_sorted_anagram_dict()
    
    ana_dict = build_anagram_dict()
    sorted_by_length =  sort(collect(ana_dict), by=x->length(x[2]), rev=true)
    return sorted_by_length
    
end

sorted_anagram_dict = build_sorted_anagram_dict()

10157-element Array{Pair{Any,Any},1}:
    "aelrst" => Any["alerts", "alters", "artels", "estral", "laster", "ratels", "salter", "slater", "staler", "stelar", "talers"]
     "aeprs" => Any["apers", "asper", "pares", "parse", "pears", "prase", "presa", "rapes", "reaps", "spare", "spear"]           
     "aelst" => Any["least", "setal", "slate", "stale", "steal", "stela", "taels", "tales", "teals", "tesla"]                    
    "aceprs" => Any["capers", "crapes", "escarp", "pacers", "parsec", "recaps", "scrape", "secpar", "spacer"]                    
    "einrst" => Any["estrin", "inerts", "insert", "inters", "niters", "nitres", "sinter", "triens", "trines"]                    
    "aeprss" => Any["aspers", "parses", "passer", "prases", "repass", "spares", "sparse", "spears"]                              
     "aelrs" => Any["arles", "earls", "lares", "laser", "lears", "rales", "reals", "seral"]                                      
     "aelps" => Any["lapse", "leaps", "pales", "peal

In [103]:
# for (key,value) in sorted_anagram_dict
#     if length(key) == 8
#         println(value)
#         break
#     end
# end

[value for (key,value) in sorted_anagram_dict if length(key) == 8][1]


7-element Array{Any,1}:
 "angriest"
 "astringe"
 "ganister"
 "gantries"
 "granites"
 "ingrates"
 "rangiest"

### Exercise 12-4

Two words form a “metathesis pair” if you can transform one into the other by swapping two letters; for example, “converse” and “conserve”. Write a program that finds all of the metathesis pairs in the dictionary. 

First, write a function `number_swapped` that takes an array of two words and checks how many letters are swapped.  And then write a program that builds up an array `metathesis_pairs`.

TIP: Don’t test all pairs of words, and don’t test all possible swaps.

You may use function `combinations(a,2)` from package `Combinatorics` to form all possible combinations of 2 elements from a sequence `a`.

Credit: This exercise is inspired by an example at http://puzzlers.org.

What about taking the anagrams and find pairs that differ by only two letters?

In [417]:
using Pkg
Pkg.add("Combinatorics")
using Combinatorics

 Resolving package versions...
  Updating `C:\Users\ST\.julia\environments\v1.2\Project.toml`
 [no changes]
  Updating `C:\Users\ST\.julia\environments\v1.2\Manifest.toml`
 [no changes]


In [418]:
test_word_array = ["acers", "acres", "cares", "carse", "escar", "races", "scare", "serac"]  
combopairs = combinations(test_word_array,2)
collect( combopairs )

28-element Array{Array{String,1},1}:
 ["acers", "acres"]
 ["acers", "cares"]
 ["acers", "carse"]
 ["acers", "escar"]
 ["acers", "races"]
 ["acers", "scare"]
 ["acers", "serac"]
 ["acres", "cares"]
 ["acres", "carse"]
 ["acres", "escar"]
 ["acres", "races"]
 ["acres", "scare"]
 ["acres", "serac"]
 ⋮                 
 ["cares", "scare"]
 ["cares", "serac"]
 ["carse", "escar"]
 ["carse", "races"]
 ["carse", "scare"]
 ["carse", "serac"]
 ["escar", "races"]
 ["escar", "scare"]
 ["escar", "serac"]
 ["races", "scare"]
 ["races", "serac"]
 ["scare", "serac"]

In [419]:
function number_swapped(wordarray)
    count = 0
    for (c1,c2) in zip(wordarray[1],wordarray[2])
        if c1 != c2
            count += 1
        end
    end
    
    return count
end

number_swapped (generic function with 1 method)

In [420]:
using Combinatorics

metathesis_pairs = []

for (key,value) in anagram_dict
    for pair in combinations(value,2)
        if number_swapped(pair) == 2
            push!(metathesis_pairs, pair)
        end
    end 
    
end

metathesis_pairs

3311-element Array{Any,1}:
 ["alef", "flea"]        
 ["feal", "leaf"]        
 ["chases", "chasse"]    
 ["hooped", "poohed"]    
 ["morn", "norm"]        
 ["netty", "tenty"]      
 ["elvers", "levers"]    
 ["levers", "revels"]    
 ["plastery", "psaltery"]
 ["boring", "robing"]    
 ["orbing", "robing"]    
 ["spited", "stiped"]    
 ["darn", "nard"]        
 ⋮                       
 ["laps", "pals"]        
 ["pals", "salp"]        
 ["salp", "slap"]        
 ["devons", "dovens"]    
 ["nipa", "pina"]        
 ["pain", "pian"]        
 ["pian", "pina"]        
 ["indent", "intend"]    
 ["speers", "sprees"]    
 ["agin", "gain"]        
 ["coinfer", "conifer"]  
 ["lota", "tola"]        

## Exercise 12-5

Here’s another Car Talk Puzzler (https://www.cartalk.com/puzzler/browse):

"What is the longest English word, that remains a valid English word, as you remove its letters one at a time?

Now, letters can be removed from either end, or the middle, but you can’t rearrange any of the letters. Every time you drop a letter, you wind up with another English word. If you do that, you’re eventually going to wind up with one letter and that too is going to be an English word—one that’s found in the dictionary. I want to know what’s the longest word and how many letters  does it have? 

I’m going to give you a little modest example: Sprite. Ok? You start off with sprite, you take a letter off, one from the interior of the word, take the r away, and we’re left with the word spite, then we take the e off the end, we’re left with spit, we take the s off, we’re left with pit, it, and I."

Write a program to find all words that can be reduced in this way, and then find the longest one.

Write a new histrogram function to show the frequency of the reducible words of a given number of letters.


TIP
This exercise is a little more challenging than most, so here are some suggestions:

1. You might want to write a function `children_words` that takes a word and computes an array of all the words that can be formed by removing one letter. These are the “children” of the word.

2. Recursively, a word is reducible if *any* of its children are reducible. As a base case, you can consider the empty string reducible.  Write a recursive function `is_reducible` that takes a word as an argument and returns `true` if the word is reducible.  If a word is not in the word dictionary, then the function should return `false` (no need to check chidren words).  

3. Our word list, words.txt, doesn’t contain single letter words. So you might want to add “I”, “a”, and the empty string.

4. To improve the performance of your program, you might want to memoize the words that are known to be reducible.

In [252]:
function build_words_dict()
    
    dict = Dict();
    
    for word in eachline("words.txt")
        dict[word] = ""
    end

    return dict
    
end

words_dict = build_words_dict();

words_dict["i"] = "";
words_dict["a"] = "";
words_dict[""] = "";

In [253]:
function children_words(word)
    
    children = []
    c_array = collect(word)
    for i in eachindex(c_array)
        temp = c_array[:]
        push!(children, join(deleteat!(temp,i)))
    end
    
    return children
end
       

children_words (generic function with 1 method)

In [254]:
children_words("test")

4-element Array{Any,1}:
 "est"
 "tst"
 "tet"
 "tes"

In [386]:
children_words("it")

2-element Array{Any,1}:
 "t"
 "i"

In [387]:
children_words("i")

1-element Array{Any,1}:
 ""

In [255]:
function is_reducible(word)
    
    #@show word
    
    if (word == "")
        return true
    end
    
    if word ∉ keys(words_dict)
        return false
    end
       
    flag = false
    for w in children_words(word)
            @show w,word
            flag = is_reducible(w) || flag
    end
    
    return flag

end   
    

is_reducible (generic function with 1 method)

In [394]:
children_words("sprite")

6-element Array{Any,1}:
 "prite"
 "srite"
 "spite"
 "sprte"
 "sprie"
 "sprit"

In [395]:
is_reducible("sprite")

(w, word) = ("prite", "sprite")
(w, word) = ("srite", "sprite")
(w, word) = ("spite", "sprite")
(w, word) = ("pite", "spite")
(w, word) = ("site", "spite")
(w, word) = ("ite", "site")
(w, word) = ("ste", "site")
(w, word) = ("sie", "site")
(w, word) = ("sit", "site")
(w, word) = ("it", "sit")
(w, word) = ("t", "it")
(w, word) = ("i", "it")
(w, word) = ("", "i")
(w, word) = ("st", "sit")
(w, word) = ("si", "sit")
(w, word) = ("i", "si")
(w, word) = ("", "i")
(w, word) = ("s", "si")
(w, word) = ("spte", "spite")
(w, word) = ("spie", "spite")
(w, word) = ("spit", "spite")
(w, word) = ("pit", "spit")
(w, word) = ("it", "pit")
(w, word) = ("t", "it")
(w, word) = ("i", "it")
(w, word) = ("", "i")
(w, word) = ("pt", "pit")
(w, word) = ("pi", "pit")
(w, word) = ("i", "pi")
(w, word) = ("", "i")
(w, word) = ("p", "pi")
(w, word) = ("sit", "spit")
(w, word) = ("it", "sit")
(w, word) = ("t", "it")
(w, word) = ("i", "it")
(w, word) = ("", "i")
(w, word) = ("st", "sit")
(w, word) = ("si", "sit")
(w

true

In [396]:
function is_reducible2(word)
    
    #@show word
    
    if (word == "")
        return true
    end
    
    if word ∉ keys(words_dict)
        return false
    end
       
    for w in children_words(word)
        #@show w,word
        if is_reducible2(w)
            #@show w
            return true
        end
    end
    
    return false

end  

is_reducible2 (generic function with 1 method)

In [399]:
is_reducible2("it")

true

In [400]:
is_reducible2("i")

true

In [401]:
children_words("sprite")

6-element Array{Any,1}:
 "prite"
 "srite"
 "spite"
 "sprte"
 "sprie"
 "sprit"

In [402]:
is_reducible2("sprite")

true

In [422]:
function reducible()
    
    reducible_array = []
    
    for word in keys(words_dict)
        if is_reducible2(word)
            push!(reducible_array,word)
        end
    end

    return reducible_array
end

@time reducible_array_wo_memo = reducible()

  1.829366 seconds (12.79 M allocations: 686.689 MiB, 11.22% gc time)


9770-element Array{Any,1}:
 "pintoes" 
 "hicks"   
 "grated"  
 "gay"     
 "pails"   
 "tapirs"  
 "twists"  
 "salting" 
 "rafted"  
 "maleate" 
 "smackers"
 "sear"    
 "team"    
 ⋮         
 "scanty"  
 "prizes"  
 "akin"    
 "witted"  
 "painting"
 "wain"    
 "fauns"   
 "leans"   
 "lap"     
 "stacker" 
 "tantras" 
 "pleaser" 

In [427]:
const known_memo = Dict()

function is_reducible_memo(word)
    
    #@show word
    global known_memo
    
    if (word == "")
        return true
    end
    
    if word ∈ keys(known_memo)
        return true
    end

    
    if word ∉ keys(words_dict)
        return false
    end

      
    for w in children_words(word)
          
        if is_reducible_memo(w)
            known_memo[word] = ""
            return true
        end
        
    end

    return false
    
end 



function reducible_memo()
    
    reducible_array = []
    
    for word in keys(words_dict)
        
        if is_reducible_memo(word)
            push!(reducible_array,word)
        end
    end

    return reducible_array
end

@time reducible_array = reducible()

  1.571879 seconds (12.79 M allocations: 686.508 MiB, 11.67% gc time)


9770-element Array{Any,1}:
 "pintoes" 
 "hicks"   
 "grated"  
 "gay"     
 "pails"   
 "tapirs"  
 "twists"  
 "salting" 
 "rafted"  
 "maleate" 
 "smackers"
 "sear"    
 "team"    
 ⋮         
 "scanty"  
 "prizes"  
 "akin"    
 "witted"  
 "painting"
 "wain"    
 "fauns"   
 "leans"   
 "lap"     
 "stacker" 
 "tantras" 
 "pleaser" 

In [365]:
# longest=""
# for word in reducible_array
#     if length(word) > length(longest)
#         longest = word
#     end
# end

# println("$longest , $(length(longest))")

sort(reducible_array, by = x->length(x), rev=true)[1]

"complecting"

In [366]:
sort(reducible_array, by = x->length(x), rev=false)[1]

""

In [367]:
function histogram_array(items) 
    d = Dict()
    for item in items
        c = length(item)
        d[c] = get(d,c,0) + 1
    end
    d
end

histogram_array (generic function with 1 method)

In [368]:
histogram_array(reducible_array)

Dict{Any,Any} with 12 entries:
  2  => 36
  11 => 1
  7  => 1885
  9  => 171
  0  => 1
  10 => 7
  8  => 837
  6  => 2666
  4  => 1329
  3  => 332
  5  => 2503
  1  => 2

In [359]:
sort(collect(histogram_array(reducible_array)))

12-element Array{Pair{Any,Any},1}:
  0 => 1   
  1 => 2   
  2 => 36  
  3 => 332 
  4 => 1329
  5 => 2503
  6 => 2666
  7 => 1885
  8 => 837 
  9 => 171 
 10 => 7   
 11 => 1   